name: GoodSleep
main: goodSleep.GoodSleep
version: 1.0.1
description: A plugin for Minecraft servers
author: Thomas Faget
website: https://github.com/thomasfaget/GoodSleep

commands:
  reload:
    description: reload the configuration file
    usage: /reload
    permission: goodSleep.reload
    permission-message: You have not the permission
  setSleepPercentage:
    description: change the value of sleep percentage
    permission: goodSleep.setSleepPercentage
    permission-message: You have not the permission

permissions:
  goodSleep.sleep:
    description: Allow the player to sleep with the plugin supervision
    default: true
  goodSleep.reload:
    description: Allow the player to use the /reload command
    default: op
  goodSleep.setSleepPercentage:
    description: Allow the player to use the /setSleepPercentage
    default: op